<?php

// CampusKart university seed dataset.
// Source: National Universities Commission (NUC) current Federal, State and Private university registers.
// Accessed September 1, 2026.
// FCT is intentionally treated as a selectable location for CampusKart.

return [
    'Bauchi' => [
        'Abubakar Tafawa Balewa University',
        'Bauchi State University, Gadau',
        'Federal University of Health Sciences, Azare, Bauchi State',
    ],
    'Kaduna' => [
        'Ahmadu Bello University',
        'Nigerian Defence Academy Kaduna',
        'Air Force Institute of Technology, Kaduna',
        'Federal University of Education, Zaria, Kaduna State',
        'Federal University of Applied Sciences, Kachia, Kaduna State',
        'Kaduna State University, Kaduna',
        'Greenfield University, Kaduna',
        'Franco British International University, Kaduna State',
        'College of Petroleum and Energy Studies, Kaduna State',
        'Tazkiyah University, Kaduna, Kaduna State',
        'Omega University Kaduna',
    ],
    'Kano' => [
        'Bayero University',
        'Yusuf Maitama Sule Federal University of Education',
        'Federal University of Science and Technology, Kabo, Kano',
        'Nigeria Police Academy Wudil',
        'Aliko Dangote university of Science & Technology, Wudil',
        'Northwest University Kano',
        'Skyline University, Kano',
        'Al-Istiqama University, Sumaila, Kano State',
        'Maryam Abacha American University of Nigeria, Kano State',
        'Capital City University, Kano State',
        'Khalifa Isiyaku Rabiu University, Kano',
        'Baba Ahmed University, Kano State',
        'Azman University, Kano State',
        'Elrazi Medical University Yargaya University, Kano State',
    ],
    'Yobe' => [
        'Federal University Gashua',
        'Yobe State University, Damaturu',
    ],
    'Delta' => [
        'Federal University of Petroleum Resources, Effurun',
        'Nigerian Maritime University Okerenkoko, Delta State',
        'Admiralty University Ibusa, Delta State',
        'Federal University of Health Sciences Kwale, Delta State',
        'Federal University of Education Pankshin, Plateau State',
        'Delta State University Abraka',
        'University of Delta, Agbor',
        'Delta University of Science and Technology, Ozoro',
        'Dennis Osadebe University, Asaba',
        'Novena University, Ogume',
        'Edwin Clark University, Kaigbodo',
        'Micheal & Cecilia Ibru University',
        'Margaret Lawrence University, Umunede, Delta State',
        'Sports University, Idumuje, Ugboko, Delta State',
        'Godday Erewa University, Sapele, Delta State',
        'Western Delta University, Oghara Delta State',
    ],
    'Ondo' => [
        'Federal University of Technology, Akure',
        'Adeyemi Federal University of Education, Ondo',
        'Olusegun Agagu University of Sc. & Tech., Okitipupa, Ondo',
        'University of Medical Sciences, Ondo City, Ondo State',
        'Wesley University Ondo',
        'Achievers University, Owo',
        'Sam Maris University, Ondo',
        'University of Fortune, Igbotako, Ondo State',
        'Millenium Crest University, Ikare Akoko, Ondo State',
        'Adekunle Ajasin University, Akungba',
    ],
    'Niger' => [
        'Federal University of Technology, Minna',
        'Federal University of Education Kontagora, Niger State',
        'Ibrahim Badamasi Babangida University, Lapai',
        'AbdulKadir Kure University, Minna Niger State',
        'Abdulsalam Abubakar University of Agriculture and Climate Action, Mokwa, Niger State',
        'Edusoko University, Bida, Niger State',
        'Newgate University, MInna, Niger State.',
        'El-Amin University, Minna, Niger State',
        'JEFAP University, Suleja, Niger State',
        'Sani Bello University, Kontagora Niger State',
    ],
    'Imo' => [
        'Federal University of Technology, Owerri',
        'Alvan Ikoku Federal University of Education, Owerri, Imo State',
        'Imo State University, Owerri',
        'Kingsley Ozumba Mbadiwe University Ogboko, Imo State',
        'University of Agriculture and Environmental Sciences Umuagwo, Imo State',
        'University of Innovation, Science and Technology, Omuma, Imo State',
        'Hezekiah University, Umudi',
        'Claretian University of Nigeria, Nekede, Imo State',
        'Bridget University Mbaise, Okirika-Nweke, Imo State',
        'Azione Verde University, Amaigbo, Imo State',
        'Maria Assumpta University Owerri, Imo State',
    ],
    'Jigawa' => [
        'Federal University, Dutse, Jigawa State',
        'Federal University of Technology, Babura, Jigawa State',
        'Sule Lamido University, Kafin Hausa, Jigawa',
        'Jigawa State University of Medical and Allied Health Sciences, Majia',
    ],
    'Katsina' => [
        'Federal University, Dutsin-Ma, Katsina',
        'Federal University of Transportation Daura, Katsina',
        'Federal University of Health Sciences, Katsina',
        'Umar Musa Yar\' Adua University Katsina',
        'Al-Qalam University, Katsina',
    ],
    'Gombe' => [
        'Federal University, Kashere, Gombe State',
        'Gombe State Univeristy, Gombe',
        'North Eastern University, Gombe',
        'Jewel University, Gombe state',
    ],
    'Nasarawa' => [
        'Federal University, Lafia, Nasarawa State',
        'Nasarawa State University Keffi',
        'Ave Maria University, Piyanko, Nasarawa State',
        'Mewar International University, Masaka, Nasarawa State',
        'Phoenix University, Agwada, Nasarawa State',
        'Bingham University, New Karu',
    ],
    'Kogi' => [
        'Federal University, Lokoja, Kogi State',
        'Prince Abubakar Audu University Anyigba',
        'Confluence University of Science and Technology Osara, Kogi',
        'Kogi State University, Kabba',
        'Al-Bayan University, Ankpa, Kogi State',
        'Salem University, Lokoja',
    ],
    'Ebonyi' => [
        'Evangel University, Akaeze',
        'Alex Ekwueme University, Ndufu-Alike, Ebonyi State',
        'Ebonyi State University, Abakaliki',
        'Ebonyi State University of ICT, Science and Technology, Oferekpe',
        'University of Aeronautics and Aerospace Engineering Ezza, Ebonyi State',
        'David Nweze Umahi Federal University of Medical Sciences, Uburu',
        'Euston University, Abakaliki, Ebonyi State',
    ],
    'Bayelsa' => [
        'Federal University, Otuoke, Bayelsa',
        'Federal University of Agriculture Bassam-Biri, Bayelsa',
        'Niger Delta University Yenagoa',
        'University of Africa Toru Orua, Bayelsa State',
        'Bayelsa Medical University',
        'Hensard University, Toru-Orua, Sagbama, Bayelsa State',
    ],
    'Ekiti' => [
        'Federal University, Oye-Ekiti, Ekiti State',
        'Federal University of Technology and Environmental Studies, Iyin-Ekiti, Ekiti State.',
        'Ekiti State University',
        'Bamidele Olumilua University of Science and Technology Ikere, Ekiti State',
        'Afe Babalola University, Ado-Ekiti - Ekiti State',
        'Elizade University, Ilara-Mokin',
        'Hillside University of Science and Technology, Okemisi, Ekiti State',
        'Venite University, Iloro-Ekiti, Ekiti State',
        'High Flyers University, Ikere-Ekiti, Ekiti State',
    ],
    'Taraba' => [
        'Kwararafa University, Wukari',
        'Federal University, Wukari, Taraba State',
        'Taraba State University, Jalingo',
        'Taraba State University of Tropical Agriculture, Science, Technology and Climate Action, Gembu',
        'Greenland University, Jalingo, Taraba State',
    ],
    'Kebbi' => [
        'Federal University, Birnin Kebbi',
        'Federal University of Agriculture, Zuru, Kebbi State',
        'Kebbi State University of Science and Technology, Aliero',
        'Rayhaan University, Kebbi',
    ],
    'Zamfara' => [
        'Federal University, Gusau Zamfara',
        'Zamfara State University',
        'Federal University of Health Science and Technology, Tsafe',
        'Huda University, Gusau, Zamafara State',
    ],
    'Abia' => [
        'Michael Okpara University of Agricultural Umudike',
        'Abia State University, Uturu',
        'Gregory University, Uturu',
        'Clifford University Owerrinta Abia State',
        'Spiritan University, Nneochi Abia State',
        'Nigerian British University, Asa, Abia State',
        'Lux Mundi University Umuahia, Abia State',
        'Amadeus University, Amizi, Abia State',
    ],
    'Adamawa' => [
        'Modibbo Adama University of Technology, Yola',
        'Federal University of Agriculture, Mubi',
        'Adamawa State University Mubi',
        'American University of Nigeria, Yola',
    ],
    'FCT' => [
        'National Open University of Nigeria, Abuja',
        'University of Abuja, Gwagwalada',
        'African Aviation and Aerospace University',
        'National University of Science and Technology, Abuja',
        'African University of Science and Technology, Abuja',
        'Veritas University, Abuja',
        'Baze University',
        'Nile University of Nigeria, Abuja',
        'Philomath University, Kuje, Abuja',
        'European University of Nigeria, Duboyi, FCT',
        'Canadian University of Nigeria, Abuja',
        'Amaj University, Kwali, Abuja',
        'Cosmopolitan University Abuja',
        'Miva Open University, Abuja FCT',
        'Al-Muhibbah Open University, Abuja',
        'Prime University, Kuje, FCT Abuja',
        'African University of Economics, FCT, Abuja',
        'Eranova University, Abuja',
        'Leadership University, Abuja',
        'City University Abuja',
        'Ummah University of Nigeria, Abuja',
    ],
    'Anambra' => [
        'Nnamdi Azikiwe University, Awka',
        'Chukwuemeka Odumegwu Ojukwu University, Uli',
        'Madonna University, Okija',
        'Paul University, Awka - Anambra State',
        'Legacy University, Okija Anambra State',
        'Tansian University, Umunya',
        'Peter University, Achina-Onneh Anambra State',
        'University on the Niger, Umunya, Anambra state',
        'Shanahan University Onitsha, Anambra State',
        'Transatlantic University of Medine and Health Sciences, Umuchukwu, Anambra State',
    ],
    'Osun' => [
        'Obafemi Awolowo University,Ile-Ife',
        'Federal University of Health Sciences, Ila Orangun, Osun State',
        'Federal University of Agriculture and Developmental Studies, Iragbuji, Osun State',
        'Osun State University Osogbo',
        'University of Ilesa, Osun State',
        'Bowen University, Iwo',
        'Redeemer\'s University, Ede',
        'Joseph Ayo Babalola University, Ikeji-Arakeji',
        'Fountain Unveristy, Oshogbo',
        'Oduduwa University, Ipetumodu - Osun State',
        'Adeleke University, Ede',
        'Kings University, Ode Omu',
        'Westland University Iwo, Osun State',
        'Minaret University, Ikirun, Osun State',
        'Owolabi University, Oke Ila Orangun',
    ],
    'Ogun' => [
        'Bells University of Technology, Otta',
        'Federal University of Agriculture, Abeokuta',
        'Federal University of Medicine and Medical Sciences, Abeokuta',
        'Olabisi Onabanjo University, Ago Iwoye',
        'Moshood Abiola University of Science and Technology Abeokuta',
        'Babcock University,Ilishan-Remo',
        'Covenant University Ota',
        'Crawford University Igbesa',
        'Mcpherson University, Seriki Sotayo, Ajebo',
        'Hallmark University, Ijebi Itele, Ogun',
        'Christopher University Mowe',
        'Mountain Top University',
        'Southwestern University, Oku Owa',
        'Trinity University Ogun State',
        'Aletheia University, Ago-Iwoye Ogun State',
        'Gerar University of Medical Science Imope Ijebu, Ogun State.',
        'New City University, Ayetoro, Ogun State',
        'Monarch University, Iyesi-Ota, Ogun State',
        'American Open University, Abeokuta, Ogun State',
        'Abdulfattah Durojaiye University, Abeokuta Ogun State',
        'Crescent University',
        'Tai Solarin Federal University of Education, Ijagun, Ijebu Ode',
        'Vision University, Ikogbo, Ogun State',
        'Mercy Medical University, Iwo, Ogun State',
    ],
    'Benue' => [
        'Joseph Sarwuan Tarka University, Makurdi',
        'Federal University of Health Sciences, Otukpo, Benue State',
        'Rev. Fr. Moses Orshio Adasu (Formerly, Benue State University), Makurdi',
        'Benue State University of Agriculture Science and Technology, Ihugh.',
        'University of Mkar, Mkar',
    ],
    'Edo' => [
        'Igbinedion University Okada',
        'University of Benin',
        'Ambrose Alli University, Ekpoma',
        'Edo State University, Iyamho',
        'Benson Idahosa University, Benin City',
        'Wellspring University, Evbuobanosa - Edo State',
        'Glorious Vision University, Ogwa, Edo State.',
        'Mudiame University, Irrua, Edo State',
        'Lighthouse University, Evbobanosa, Edo State',
        'Tonine Iredia University of Communication, Benin City, Edo State',
        'Adeche Momoh University, Igarra, Edo State',
    ],
    'Cross River' => [
        'University of Calabar',
        'University of Cross River State, Calabar',
        'Cross River University of Education and Entrepeneurship, Akampa, Cross River State',
        'Arthur Javis University Akpoyubo Cross river State',
        'Havilla University, Nde-Ikom, Cross River State',
        'British Canadian University, Obufu Cross River State',
        'The Duke Medical University, Calabar, Cross River State',
        'Pearl University, Calabar, Cross river',
    ],
    'Oyo' => [
        'University of Ibadan',
        'Federal University of Agriculture and Technology Okeho, Oyo State',
        'Ladoke Akintola University of Technology, Ogbomoso',
        'First Technical University Ibadan',
        'Emanuel Alayande University of Education Oyo',
        'Ajayi Crowther University, Ibadan',
        'Lead City University, Ibadan',
        'Kola Daisi University Ibadan, Oyo State',
        'Dominican University Ibadan Oyo State',
        'Precious Cornerstone University, Oyo',
        'Atiba University Oyo',
        'Dominion University Ibadan, Oyo State',
        'West Midlands Open University, Ibadan, Oyo State',
    ],
    'Kwara' => [
        'University of Ilorin',
        'Kwara State University, Ilorin',
        'Kwara State University of Education, Ilorin, Kwara State',
        'Ojaja University Eiyenkorin, Kwara State',
        'Thomas Adewumi University, Oko-Irese, Kwara State',
        'Ahman Pategi University, Kwara State',
        'University of Offa, Kwara State',
        'Al-Hikmah University, Ilorin',
        'Landmark University, Omu-Aran.',
        'Summit University, Offa',
        'Muhammad Kamalud University Kwara',
        'Abdulrasaq Abubakar Toyin University, Oke-Ogba, Ganmo, Ilorin, Kwara State',
        'Lens University, Ilemona, Kwara State',
        'Jimoh Babalola University, Ilorin, Kwara State',
    ],
    'Plateau' => [
        'University of Jos',
        'Plateau State University Bokkos',
        'Karl-Kumm University, Vom, Plateau State',
        'Anan University, Kwall, Plateau State',
    ],
    'Lagos' => [
        'University of Lagos',
        'Federal University of Science and Technology, Epe',
        'Lagos State University, Ojo',
        'Lagos State University of Education, Ijanikin',
        'Lagos State University of Science and Technology Ikorodu',
        'Pan-Atlantic University, Lagos',
        'Caleb University, Lagos',
        'Augustine University',
        'Chrisland University',
        'Anchor University Ayobo Lagos State',
        'Maranatha University, Lagos',
        'James Hope University, Lagos, Lagos State',
        'Eko University of Medical and Health Sciences Ijanikin, Lagos',
        'Nigerian University of Technology and Management, Apapa, Lagos State',
        'Isaac Balami University of Aeronautics and Management, Lagos State',
        'Unique Open University, Ojo, Lagos State',
        'Regnum Medical University, Anthony, Lagos State',
    ],
    'Borno' => [
        'University of Maiduguri',
        'Kashim Ibrahim ( formerly Bornu State) University, Maiduguri',
        'Al-Ansar University, Maiduguri, Borno',
        'Nigerian Army University Biu',
    ],
    'Enugu' => [
        'University of Nigeria, Nsukka',
        'Federal University of Allied Health Sciences, Enugu',
        'Enugu State University of Science and Technology, Enugu',
        'State University of Medical and Applied Sciences, Igbo-Eno, Enugu',
        'Caritas University, Enugu',
        'Renaissance University, Enugu',
        'Godfrey Okoye University, Ugwuomu-Nike - Enugu State',
        'Coal City University Enugu State',
        'Maduka University, Ekwegbe, Enugu State',
        'PeaceLand University, Enugu State',
        'Kevin Eze University, Mgbowo, Enugu State',
    ],
    'Rivers' => [
        'University of Port-Harcourt',
        'Federal University of Environment and Technology, Tai Town, Ogoniland, Rivers State',
        'Rivers State University',
        'Ignatius Ajuru University of Education,Rumuolumeni',
        'Rhema University, Obeama-Asa - Rivers State',
        'PAMO University of Medical Sciences, Portharcourt',
        'Wigwe University, Isiokpo Rivers State',
    ],
    'Akwa Ibom' => [
        'University of Uyo',
        'Federal University of Technology, Ikot Abasi, Akwa Ibom State',
        'University of Maritime Studies, Oron, Akwa Ibom State',
        'Federal University of Agriculture and Technology Obio-Akpa Akwa Ibom State',
        'Akwa Ibom State University, Ikot Akpaden',
        'Obong University, Obong Ntak',
        'Ritman University, Ikot Ekpene, Akwa Ibom',
        'Topfaith University, Mkpatak, Akwa Ibom State',
        'Southern Atlantic University, Uyo, Akwa Ibom State',
    ],
    'Sokoto' => [
        'Usumanu Danfodiyo University',
        'Sokoto State University',
        'Shehu Shagari University of Education, Sokoto',
        'Saisa University of Medical Sciences and Technology, Sokoto State',
        'NorthWest University Sokoto State',
        'Iconic Open University, Sokoto State.',
    ],
];
